language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install -e . --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - py.test --doctest-modules --pep8 trakt -v --cov trakt --cov-report term-missing
after_success:
  - coveralls
